### ISSUE TITLE
Impossible de valider le panier quand il y a trop d'items dans le panier actuel

### ISSUE THREAD

**Issue by Esteban795** [Esteban795/PP2I1#10]
![Screenshot from 2023-12-05 12-58-55](https://github.com/Esteban795/PP2I1/assets/58440121/e82a2684-dd58-4db9-a142-300100195439)

Impossible de valider le panier parce que le bouton est caché par les items

**Comment by BTom-GH** [comment]
Voila j'ai fix l'issue !
