### ISSUE TITLE
Petite erreur dans le retour sur la TODOLIST la team

### ISSUE THREAD

**Issue by BTom-GH** [Esteban795/PP2I1#11]
Euh le panier a été fait 🤓

**Comment by Esteban795** [comment]
Espèce de golmon on parle de la backend

**Comment by BTom-GH** [comment]
Dans ce cas il faut le préciser🤓

**Comment by Esteban795** [comment]
shut up nerd

**Comment by BTom-GH** [comment]
Apprend a lire mon gars. Tu sais pas a qui tu parles. Je monte une équipe.

**Comment by Esteban795** [comment]
Baptiste a fix, c'est bon,
