### ISSUE TITLE
Page du shop : scrollbar horizontal qui apparaît quand le panier est vide

### ISSUE THREAD

**Issue by Esteban795** [Esteban795/PP2I1#12]
- [x] Y a une scrollbar louche qui apparaît quand le panier est vide et que tu hover dessus
- [x]  Sortir le bouton valider de la partie qui scroll, et le mettre en dehors de sorte à ce qu'il soit toujours visible.
- [x] Mettre le montant total du panier

![Screenshot from 2023-12-13 14-18-58](https://github.com/Esteban795/PP2I1/assets/58440121/67db2656-b50a-41a2-be38-99f5af402cc7)

**Comment by BTom-GH** [comment]
C'est bon normalement, on peut encore éventuellement peaufiner à coup de flexbox pour mieux aligner le total avec le bouton etc mais globalement c'est fix

**Comment by Esteban795** [comment]
it's fixed, but at what cost ? y a une scrollbar horizontale sur les produits maintenant

**Comment by BTom-GH** [comment]
![Fsu1I9lXsAUQKCa](https://github.com/Esteban795/PP2I1/assets/61981635/f3301dc3-42ac-47a8-bf2f-02590c8a9102)
